### ISSUE TITLE
[BUG] Creating new environment Internal server error 

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#257]
**Describe the bug**
The API is returning Internal server error when all environment are `isActive=false` and the user tries to create a fresh new one.

**To Reproduce**
1. Post `/api/lzmetadataEnv/?readActiveOnly=true&bulkDelete=true`
```json
[]
```
1. Post `/api/lzmetadataEnv/?readActiveOnly=true&bulkDelete=true`
```json
[{"id":0,"isActive":true,"name":"new"}]
```

**Expected behavior**
The API should create a new environment and return the JSON with actual id as usual.

E. g.:
```json
[{"id":7,"isActive":true,"name":"new"}]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5604834/84600641-3996f580-ae51-11ea-8340-6e183a800f57.png)

**Additional context**

**Logs**
```
houston-service_1  | ERROR:config:Exception on /api/lzmetadataEnv/ [POST]
houston-service_1  | Traceback (most recent call last):
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
houston-service_1  |     response = self.full_dispatch_request()
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
houston-service_1  |     rv = self.handle_user_exception(e)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
houston-service_1  |     reraise(exc_type, exc_value, tb)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
houston-service_1  |     raise value
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
houston-service_1  |     rv = self.dispatch_request()
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
houston-service_1  |     return self.view_functions[rule.endpoint](**req.view_args)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
houston-service_1  |     response = function(request)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
houston-service_1  |     response = function(request)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
houston-service_1  |     response = function(request)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
houston-service_1  |     return function(request)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
houston-service_1  |     return function(**kwargs)
houston-service_1  |   File "/srv/tb_houston_service/lzmetadata_env.py", line 109, in create_all
houston-service_1  |     logical_delete_all_active()
houston-service_1  |   File "/srv/tb_houston_service/lzmetadata_env.py", line 93, in logical_delete_all_active
houston-service_1  |     db.session.add(o)
houston-service_1  | UnboundLocalError: local variable 'o' referenced before assignment
```

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/66

**Comment by karwootang-gft** [comment]
I just want to clarify this behaviour.

If you want to create a new object, you shouldn't pass in the id:
e.g.

[{"isActive":true,"name":"new"}]

If you pass in the id, it will try to update the object with id, and will fail if the object doesn't exist.

[{"id":0,"isActive":true,"name":"new"}]

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

> If you pass in the id, it will try to update the object with id, and will fail if the object doesn't exist.

`id:0` should have the same behavior as 'not passing in the id'.

With or without `id:0` it is causing internal server error:

![image](https://user-images.githubusercontent.com/5604834/84657377-8f6bac00-aeea-11ea-8a06-9ea6c25e94bb.png)
