### ISSUE TITLE
[BUG] Creating new lanVPC Internal server error

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#258]
**Describe the bug**
The API is returning Internal server error when all LanVPCs are `isActive=false` and the user tries to create a fresh new one.

**To Reproduce**
1. Post `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`
```json
[]
```
1. Post `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`
```json
[
  {
    "environments": [],
    "isActive": true,
    "name": "development"
  }
]
```

**Expected behavior**
The API should create a new environment and return the JSON with actual id as usual.

E. g.:
```json
[
  {
    "id": 3,
    "environments": [],
    "isActive": true,
    "name": "development"
  }
]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5604834/84600819-8a5b1e00-ae52-11ea-9efa-a82a6ef7b634.png)

**Additional context**
```
houston-service_1  | UnboundLocalError: local variable 'o' referenced before assignment
houston-service_1  | ERROR:config:Exception on /api/lzmetadataLanVpc/ [POST]
houston-service_1  | Traceback (most recent call last):
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
houston-service_1  |     response = self.full_dispatch_request()
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
houston-service_1  |     rv = self.handle_user_exception(e)
houston-service_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
houston-service_1  |     reraise(exc_type, exc_value, tb)
```

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/66
