### ISSUE TITLE
[BUG] Application deployment not working

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#373]
**Describe the bug**
When uers try to deploy applications it fails with an exception

**To Reproduce**
1. Add a new app to Solution
1. Try to deploy
1. See the error

**Expected behavior**
Users must be able to deploy applications

**Additional context**
```
2020-09-02 15:34:31,969 INFO sqlalchemy.engine.base.Engine ROLLBACK
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f3b186b4358 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/site-packages/flask_executor/executor.py", line 35, in propagate_exceptions_callback
    raise exc
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_executor/executor.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/ctx.py", line 158, in wrapper
    return f(*args, **kwargs)
  File "/srv/tb_houston_service/application_deployment.py", line 93, in start_deployment
    response = deploy_application(app_dep, dbsession = dbs)
  File "/srv/tb_houston_service/application_deployment.py", line 257, in deploy_application
    app_deployment.activatorGitUrl = act.activatorLink
AttributeError: 'Activator' object has no attribute 'activatorLink'
```

**Comment by Salles-FA** [comment]
Created new docker image:
- gcr.io/tranquility-base-images/tb-houston-service:review
