### ISSUE TITLE
[BUG] "api/activatorOnboard/" Internal server error 

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#523]
**Describe the bug**
The server is returning 500 "Internal Server Error" when calling `api/activatorOnboard/` method

**To Reproduce**
1. Initialize an Activator using Admin user
2. Fill in the variables
3. Submit the Form
4. Chose to onboard the activator
5. See the error

**Expected behavior**
The API should call DaC and follow the usual onboarding workflow

**Comment by Salles-FA** [comment]
Analyzing the logs
```sh
2021-02-05 11:58:58,216 INFO sqlalchemy.engine.base.Engine ROLLBACK
ERROR:tb_houston_service.activator:repo name from url invalid, is activator 'draft'?
Traceback (most recent call last):
  File "/usr/src/app/tb_houston_service/activator.py", line 594, in onboard
    ret = post_repo_data_to_dac(oid, user.id)
  File "/usr/src/app/tb_houston_service/activator.py", line 553, in post_repo_data_to_dac
    raise Exception("repo name from url invalid, is activator 'draft'?")
Exception: repo name from url invalid, is activator 'draft'?
```

This error message isn't reflecting the actual error because the url is valid, confirmed by directly querying the DB.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-gcp/issues/604
